version: "3.0"  # Puedes cambiar la versión según tus necesidades

services:
  postgres:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: shgzj
      POSTGRES_PASSWORD: shgzj
      POSTGRES_DB: postgres
    restart: unless-stopped
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nestjs:
    container_name: nestjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - postgres
    environment:
      HOST_DATABASE: database
      PORT_DATABASE: 5432
      USER_DATABASE: shgzj
      USER_PASSWORD: shgzj
      NAME_DATABASE: postgres
      SECRET_KEY: shgzjxd
      JWT_EXPIRATION_TIME: 2h
    volumes:
      - certifieds_data:/app/src/public/certifieds

volumes:
  postgres_data:
    driver: local
  certifieds_data:
    driver: local